# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'WorkShop' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Firebase/Messaging'
  # Pods for WorkShop

  target 'WorkShop-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    # pod 'react-native-video', :path => '../node_modules/react-native-video'
    # pod 'react-native-fetch-blob',
    # :path => '../node_modules/react-native-fetch-blob'
    # pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'


  end

  target 'WorkShopTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'WorkShop-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!



end
