//login types
export const LOGIN_ACTION_TYPES = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_REQUEST_SUCCESS: 'LOGIN_REQUEST_SUCCESS',
    LOGIN_REQUEST_FAIL: 'LOGIN_REQUEST_FAIL',
    LOGOUT_REQUEST_SUCCESS : 'LOGOUT_REQUEST_SUCCESS',
    CLEAR_MESSAGE : 'CLEAR_MESSAGE'
}
//signup types
export const SIGNUP_ACTION_TYPES = {
    SIGNUP_REQUEST: 'SIGNUP_REQUEST',
    SIGNUP_REQUEST_SUCCESS: 'SIGNUP_REQUEST_SUCCESS',
    SIGNUP_REQUEST_FAIL: 'SIGNUP_REQUEST_FAIL'
}
